import type { WorkerFeedSource } from "./feedTypes";

export const workerFeedSources: WorkerFeedSource[] = [
  {
    id: "nhc-epac-en",
    name: "NHC Eastern Pacific",
    category: "weather",
    kind: "rss",
    url: "https://www.nhc.noaa.gov/index-ep.xml",
    priority: 10,
    enabled: true,
    tags: ["official", "hurricane", "pacific"],
  },
  {
    id: "nhc-epac-es",
    name: "NHC Eastern Pacific Spanish",
    category: "weather",
    kind: "rss",
    url: "https://www.nhc.noaa.gov/index-ep-sp.xml",
    priority: 10,
    enabled: true,
    tags: ["official", "huracan", "pacifico"],
  },
  {
    id: "smn-conagua-alerts",
    name: "SMN CONAGUA Alerts",
    category: "weather",
    kind: "rss",
    url: "https://correo1.conagua.gob.mx/feedsmn/feedalert.aspx",
    priority: 9,
    enabled: true,
    tags: ["official", "mexico", "weather"],
  },
  {
    id: "vallarta-daily-pv",
    name: "Vallarta Daily Puerto Vallarta",
    category: "local",
    kind: "rss",
    url: "https://www.vallartadaily.com/category/puerto-vallarta-news/feed/",
    priority: 4,
    enabled: true,
    tags: ["local", "puerto-vallarta", "news"],
  },
];

export const urgencyKeywords = [
  "huracan",
  "huracán",
  "tormenta tropical",
  "Puerto Vallarta",
  "Jalisco",
  "evacuacion",
  "evacuación",
  "inundacion",
  "inundación",
  "marejada",
  "hurricane",
  "tropical storm",
  "flood",
  "surge",
  "evacuation",
];
