import type { DashboardConfig } from "./types";

const utcHour = new Date().toISOString().slice(11, 13);

export const defaultConfig: DashboardConfig = {
  site: {
    title: "Emergency Weather Dashboard",
    callSign: "XE1CPM - DL70ir",
    locationName: "Puerto Vallarta, Jalisco",
    timezone: "America/Bahia_Banderas",
    language: "en",
  },
  workerEndpoint: "/api",
  socialMonitoringEnabled: false,
  urgencyKeywords: [
    "huracan",
    "huracán",
    "tormenta tropical",
    "Puerto Vallarta",
    "Jalisco",
    "evacuacion",
    "evacuación",
    "inundacion",
    "inundación",
    "marejada",
    "hurricane",
    "tropical storm",
    "flood",
    "surge",
    "evacuation",
  ],
  tiles: [
    {
      id: "radar",
      title: "Radar",
      group: "weather",
      refreshSeconds: 3600,
      enabled: true,
      sources: [
        { kind: "image", url: "https://cdn.star.nesdis.noaa.gov/GOES16/ABI/SECTOR/mex/13/GOES16-MEX-13-1000x1000.gif" },
        { kind: "image", url: "https://cdn.star.nesdis.noaa.gov/GOES19/ABI/SECTOR/GA/13/GOES19-GA-13-1000x1000.gif" },
      ],
    },
    {
      id: "cams",
      title: "Cams",
      group: "local",
      refreshSeconds: 10,
      enabled: true,
      sources: [{ kind: "image", url: "https://webcamsdemexico.net/puertovallarta5/live.jpg" }],
    },
    {
      id: "tropical",
      title: "Tropical Activity",
      group: "weather",
      refreshSeconds: 600,
      enabled: true,
      sources: [
        { kind: "image", url: "https://www.nhc.noaa.gov/xgtwo/two_pac_0d0.png" },
        { kind: "image", url: "https://www.nhc.noaa.gov/xgtwo/two_pac_7d0.png" },
      ],
    },
    {
      id: "propagation",
      title: "HF Propagation",
      group: "radio",
      refreshSeconds: 900,
      enabled: true,
      sources: [
        { kind: "image", url: `https://img.propagation.dr2w.de/n-america/10M/dr2w_10M_${utcHour}.png` },
        { kind: "image", url: `https://img.propagation.dr2w.de/n-america/20M/dr2w_20M_${utcHour}.png` },
        { kind: "image", url: `https://img.propagation.dr2w.de/n-america/40M/dr2w_40M_${utcHour}.png` },
      ],
    },
    {
      id: "live-video",
      title: "Live Video",
      group: "news",
      refreshSeconds: 600,
      enabled: true,
      sources: [
        { kind: "iframe", url: "https://www.youtube.com/embed/5boZ1Vw95OU" },
        { kind: "iframe", url: "https://www.youtube.com/embed/roYcxYa6izQ" },
      ],
    },
    {
      id: "wind-rain-forecast",
      title: "Wind + Rain",
      group: "weather",
      refreshSeconds: 1800,
      enabled: true,
      sources: [
        {
          kind: "iframe",
          url: "https://embed.windy.com/embed2.html?lat=20.65&lon=-105.22&zoom=6&level=surface&overlay=rain&product=ecmwf",
        },
        {
          kind: "iframe",
          url: "https://embed.windy.com/embed2.html?lat=20.65&lon=-105.22&zoom=6&level=surface&overlay=wind&product=ecmwf",
        },
      ],
    },
  ],
  feeds: [
    {
      id: "nhc-epac-en",
      name: "NHC Eastern Pacific",
      category: "weather",
      kind: "rss",
      url: "https://www.nhc.noaa.gov/index-ep.xml",
      priority: 10,
      enabled: true,
      tags: ["official", "hurricane", "pacific"],
    },
    {
      id: "nhc-epac-es",
      name: "NHC Eastern Pacific Spanish",
      category: "weather",
      kind: "rss",
      url: "https://www.nhc.noaa.gov/index-ep-sp.xml",
      priority: 10,
      enabled: true,
      tags: ["official", "huracan", "pacifico"],
    },
    {
      id: "smn-conagua-alerts",
      name: "SMN CONAGUA Alerts",
      category: "weather",
      kind: "rss",
      url: "https://correo1.conagua.gob.mx/feedsmn/feedalert.aspx",
      priority: 9,
      enabled: true,
      tags: ["official", "mexico", "weather"],
    },
    {
      id: "vallarta-daily-pv",
      name: "Vallarta Daily Puerto Vallarta",
      category: "local",
      kind: "rss",
      url: "https://www.vallartadaily.com/category/puerto-vallarta-news/feed/",
      priority: 4,
      enabled: true,
      tags: ["local", "puerto-vallarta", "news"],
    },
  ],
};
