import type { DashboardConfig } from "./types";

const utcHour = new Date().toISOString().slice(11, 13);

export const defaultConfig: DashboardConfig = {
  site: {
    title: "Emergency Weather Dashboard",
    callSign: "XE1CPM - DL70ir",
    locationName: "Puerto Vallarta, Jalisco",
    timezone: "America/Bahia_Banderas",
    language: "en",
  },
  workerEndpoint: "/api",
  socialMonitoringEnabled: false,
  emergencyLinks: [
    {
      id: "live-situation",
      title: "Live Situation",
      links: [
        {
          id: "iris-seismic-monitor",
          label: "IRIS Seismic Monitor",
          url: "https://www.iris.edu/app/seismic-monitor/map?lat=21.1159&lng=-106.4146&zoom=6",
          description: "Regional seismic activity map near Puerto Vallarta.",
          kind: "map",
        },
        {
          id: "nasa-firms",
          label: "NASA FIRMS Fire Map",
          url: "https://firms.modaps.eosdis.nasa.gov/map/#d:24hrs;@-104.0,21.4,7.1z",
          description: "Satellite-detected fires and hotspots in the region.",
          kind: "map",
        },
        {
          id: "ssn-mexico",
          label: "Servicio Sismologico Nacional Mexico",
          url: "https://www.ssn.unam.mx/",
          description: "Official Mexico seismic monitoring and reports.",
          kind: "official",
        },
        {
          id: "usgs-latest-earthquakes",
          label: "USGS Latest Earthquakes",
          url: "https://earthquake.usgs.gov/earthquakes/map/",
          description: "Global earthquake map from the USGS.",
          kind: "map",
        },
        {
          id: "semar-tsunami-alerts",
          label: "SEMAR Centro de Alerta de Tsunamis",
          url: "https://diredimoat.semar.gob.mx/cat/centroAlertasTsunamis.html",
          description: "Official Mexican tsunami alert center.",
          kind: "official",
        },
        {
          id: "cenapred-atlas",
          label: "CENAPRED Atlas Nacional de Riesgos",
          url: "https://www.atlasnacionalderiesgos.gob.mx/",
          description: "National risk atlas for hazards in Mexico.",
          kind: "official",
        },
      ],
    },
    {
      id: "weather-storms",
      title: "Weather + Storms",
      links: [
        {
          id: "smn-conagua",
          label: "SMN / CONAGUA",
          url: "https://smn.conagua.gob.mx/",
          description: "Official Mexico weather forecasts and warnings.",
          kind: "official",
        },
        {
          id: "nhc-eastern-pacific",
          label: "National Hurricane Center Eastern Pacific",
          url: "https://www.nhc.noaa.gov/?epac",
          description: "Eastern Pacific tropical cyclone outlooks.",
          kind: "official",
        },
        {
          id: "windy-puerto-vallarta",
          label: "Windy Puerto Vallarta",
          url: "https://www.windy.com/?20.653,-105.225,7",
          description: "Interactive wind, rain, and forecast map.",
          kind: "map",
        },
      ],
    },
    {
      id: "local-official",
      title: "Local Official",
      links: [
        {
          id: "proteccion-civil-jalisco",
          label: "Proteccion Civil Jalisco",
          url: "https://proteccioncivil.jalisco.gob.mx/",
          description: "Jalisco civil protection updates and resources.",
          kind: "official",
        },
        {
          id: "bomberos-puerto-vallarta",
          label: "Bomberos / Proteccion Civil Puerto Vallarta",
          url: "https://bomberos.puertovallarta.gob.mx/",
          description: "Puerto Vallarta fire and civil protection resources.",
          kind: "official",
        },
        {
          id: "cnpc",
          label: "Coordinacion Nacional de Proteccion Civil",
          url: "https://cnpcinforma.sspc.gob.mx/Proteccioncivil.html",
          description: "National civil protection information for Mexico.",
          kind: "official",
        },
        {
          id: "cruz-roja-mexicana",
          label: "Cruz Roja Mexicana",
          url: "https://www.cruzrojamexicana.org.mx/",
          description: "Mexican Red Cross emergency and support resources.",
          kind: "official",
        },
      ],
    },
    {
      id: "preparedness-library",
      title: "Preparedness Library",
      links: [
        {
          id: "ready-gov",
          label: "Ready.gov",
          url: "https://www.ready.gov/",
          description: "Preparedness guidance for common emergencies.",
          kind: "preparedness",
        },
        {
          id: "red-cross-preparedness",
          label: "American Red Cross Preparedness",
          url: "https://www.redcross.org/get-help/how-to-prepare-for-emergencies.html",
          description: "Emergency preparation guidance from the Red Cross.",
          kind: "preparedness",
        },
        {
          id: "vivarca",
          label: "Vivarca Offline Survival Library",
          url: "https://vivarca.org/",
          description: "Offline library for preparedness and survival references.",
          kind: "preparedness",
        },
        {
          id: "survival-data",
          label: "jorgecedi/Survival-Data",
          url: "https://github.com/jorgecedi/Survival-Data",
          description: "Community-maintained survival and preparedness data.",
          kind: "community",
        },
        {
          id: "awesome-disastertech",
          label: "awesome-disastertech",
          url: "https://github.com/DisasterTechCrew/awesome-disastertech",
          description: "Community list of disaster technology resources.",
          kind: "community",
        },
        {
          id: "awesome-survival",
          label: "awesome-survival",
          url: "https://github.com/alx-xlx/awesome-survival",
          description: "Community list of survival and preparedness resources.",
          kind: "community",
        },
      ],
    },
  ],
  urgencyKeywords: [
    "huracan",
    "huracán",
    "tormenta tropical",
    "Puerto Vallarta",
    "Jalisco",
    "evacuacion",
    "evacuación",
    "inundacion",
    "inundación",
    "marejada",
    "hurricane",
    "tropical storm",
    "flood",
    "surge",
    "evacuation",
  ],
  tiles: [
    {
      id: "radar",
      title: "Radar",
      group: "weather",
      refreshSeconds: 3600,
      enabled: true,
      sources: [
        { kind: "image", url: "https://cdn.star.nesdis.noaa.gov/GOES16/ABI/SECTOR/mex/13/GOES16-MEX-13-1000x1000.gif" },
        { kind: "image", url: "https://cdn.star.nesdis.noaa.gov/GOES19/ABI/SECTOR/GA/13/GOES19-GA-13-1000x1000.gif" },
      ],
    },
    {
      id: "cams",
      title: "Cams",
      group: "local",
      refreshSeconds: 10,
      enabled: true,
      sources: [{ kind: "image", url: "https://webcamsdemexico.net/puertovallarta5/live.jpg" }],
    },
    {
      id: "tropical",
      title: "Tropical Activity",
      group: "weather",
      refreshSeconds: 600,
      enabled: true,
      sources: [
        { kind: "image", url: "https://www.nhc.noaa.gov/xgtwo/two_pac_0d0.png" },
        { kind: "image", url: "https://www.nhc.noaa.gov/xgtwo/two_pac_7d0.png" },
      ],
    },
    {
      id: "propagation",
      title: "HF Propagation",
      group: "radio",
      refreshSeconds: 900,
      enabled: true,
      sources: [
        { kind: "image", url: `https://img.propagation.dr2w.de/n-america/10M/dr2w_10M_${utcHour}.png` },
        { kind: "image", url: `https://img.propagation.dr2w.de/n-america/20M/dr2w_20M_${utcHour}.png` },
        { kind: "image", url: `https://img.propagation.dr2w.de/n-america/40M/dr2w_40M_${utcHour}.png` },
        { kind: "image", url: "https://www.hamqsl.com/solar100sc.php" },
      ],
    },
    {
      id: "live-video",
      title: "Live Video",
      group: "news",
      refreshSeconds: 600,
      enabled: true,
      sources: [
        { kind: "iframe", url: "https://www.youtube.com/embed/5boZ1Vw95OU" },
        { kind: "iframe", url: "https://www.youtube.com/embed/roYcxYa6izQ" },
        { kind: "iframe", url: "https://www.youtube.com/embed/G5Rzz2JrmQ4" },
        { kind: "iframe", url: "https://www.youtube.com/embed/yIi9Rsl7KQ8" },
      ],
    },
    {
      id: "wind-rain-forecast",
      title: "Wind + Rain",
      group: "weather",
      refreshSeconds: 1800,
      enabled: true,
      sources: [
        {
          kind: "iframe",
          url: "https://embed.windy.com/embed2.html?lat=20.65&lon=-105.22&zoom=6&level=surface&overlay=rain&product=ecmwf",
        },
        {
          kind: "iframe",
          url: "https://embed.windy.com/embed2.html?lat=20.65&lon=-105.22&zoom=6&level=surface&overlay=wind&product=ecmwf",
        },
      ],
    },
  ],
  feeds: [
    {
      id: "nhc-epac-en",
      name: "NHC Eastern Pacific",
      category: "weather",
      kind: "rss",
      url: "https://www.nhc.noaa.gov/index-ep.xml",
      priority: 10,
      enabled: true,
      tags: ["official", "hurricane", "pacific"],
    },
    {
      id: "nhc-epac-es",
      name: "NHC Eastern Pacific Spanish",
      category: "weather",
      kind: "rss",
      url: "https://www.nhc.noaa.gov/index-ep-sp.xml",
      priority: 10,
      enabled: true,
      tags: ["official", "huracan", "pacifico"],
    },
    {
      id: "smn-conagua-alerts",
      name: "SMN CONAGUA Alerts",
      category: "weather",
      kind: "rss",
      url: "https://correo1.conagua.gob.mx/feedsmn/feedalert.aspx",
      priority: 9,
      enabled: true,
      tags: ["official", "mexico", "weather"],
    },
    {
      id: "vallarta-daily-pv",
      name: "Vallarta Daily Puerto Vallarta",
      category: "local",
      kind: "rss",
      url: "https://www.vallartadaily.com/category/puerto-vallarta-news/feed/",
      priority: 4,
      enabled: true,
      tags: ["local", "puerto-vallarta", "news"],
    },
  ],
};
